// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice = CallToActionSlimSlice | StaticBannerSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = HomeDocument;

/**
 * Primary content in *CallToActionSlim → Primary*
 */
export interface CallToActionSlimSliceDefaultPrimary {
  /**
   * Main Text field in *CallToActionSlim → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_slim.primary.main_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  main_text: prismic.KeyTextField;

  /**
   * Button Text field in *CallToActionSlim → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_slim.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *CallToActionSlim → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action_slim.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Default variation for CallToActionSlim Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlimSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSlimSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CallToActionSlim*
 */
type CallToActionSlimSliceVariation = CallToActionSlimSliceDefault;

/**
 * CallToActionSlim Shared Slice
 *
 * - **API ID**: `call_to_action_slim`
 * - **Description**: CallToActionSlim
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlimSlice = prismic.SharedSlice<
  "call_to_action_slim",
  CallToActionSlimSliceVariation
>;

/**
 * Primary content in *StaticBanner → Primary*
 */
export interface StaticBannerSliceDefaultPrimary {
  /**
   * Background Image field in *StaticBanner → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: static_banner.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Main Title field in *StaticBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: static_banner.primary.main_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  main_title: prismic.KeyTextField;

  /**
   * Secondary Title field in *StaticBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: static_banner.primary.secondary_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  secondary_title: prismic.KeyTextField;

  /**
   * Main Text field in *StaticBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: static_banner.primary.main_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  main_text: prismic.KeyTextField;
}

/**
 * Default variation for StaticBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StaticBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StaticBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *StaticBanner*
 */
type StaticBannerSliceVariation = StaticBannerSliceDefault;

/**
 * StaticBanner Shared Slice
 *
 * - **API ID**: `static_banner`
 * - **Description**: StaticBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StaticBannerSlice = prismic.SharedSlice<
  "static_banner",
  StaticBannerSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      CallToActionSlimSlice,
      CallToActionSlimSliceDefaultPrimary,
      CallToActionSlimSliceVariation,
      CallToActionSlimSliceDefault,
      StaticBannerSlice,
      StaticBannerSliceDefaultPrimary,
      StaticBannerSliceVariation,
      StaticBannerSliceDefault,
    };
  }
}
