// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action_slim: dynamic(() => import("./CallToActionSlim")),
  static_banner: dynamic(() => import("./StaticBanner")),
};
